-- BigQuery のクエリエディタに貼り付け
CREATE OR REPLACE TABLE
  `nomadic-archway-456310-g5.analytics_486730796.page_views_summary` AS
SELECT
  user_pseudo_id,
  event_name,
  event_timestamp,
  TIMESTAMP_MICROS(event_timestamp) AS event_datetime,  -- ★追加！
  geo.country,
  device.category AS device_category
FROM
  `nomadic-archway-456310-g5.analytics_486730796.events_*`
WHERE
  event_name = 'page_view';
